name: Publish binaries on release
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v1
      - name: run go get command
        run: go get -u github.com/gobuffalo/buffalo-auth
      - uses: ./.github/builder
      - uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: .release
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: binaries
          path: .release
      - name: github-upload-release
        uses: docker://moonswitch/github-upload-release:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: not actor nektos/act

